spring:
  application:
    name: ai-nocode-generator-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ai_nocode_generator?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      timeout: 5000ms
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  # Session 配置
  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: ai:nocode:session
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        name: SESSIONID
        http-only: true
        secure: false
        same-site: lax
        max-age: 1800

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liud.ainocodegenerator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-6351e168f77c4312b6ddf96868161a5d
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-6351e168f77c4312b6ddf96868161a5d
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json_object
      strict-json-schema: true

